# Ch02. Numpy의 이해

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3]) # 1차원 배열 생성
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array([[2,3,4], [4,5,6]]) # 넘파이 ndarray 객체 생성
# a 객체의 차원, 차원의 크기, 원소의 수, 자료형
a.ndim, a.shape, a.size, a.dtype

(2, (2, 3), 6, dtype('int64'))

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# 1. reshape() – 배열의 모양 변경
reshaped = a.reshape(3, 2)
print("reshape:\n", reshaped)

# 2. transpose() – 배열 전치 (행 ↔ 열)
transposed = a.transpose()
print("transpose:\n", transposed)

# 3. astype() – 자료형 변경
as_float = a.astype(float)
print("astype(float):\n", as_float)

# 4. copy() – 배열 복사 (깊은 복사)
# copied = a(얕은 복사: 복제본과 원본이 값이 같음)
copied = a.copy()
copied[0, 0] = 999
print("original a:\n", a)
print("copied (changed):\n", copied)

# 5. sum() – 배열 요소의 합 (전체 또는 축별)
#axis=0 은 열단위, 1은 행단위
total_sum = a.sum()
row_sum = a.sum(axis=1)
print("sum (전체):", total_sum)
print("sum (행별):", row_sum)

reshape:
 [[1 2]
 [3 4]
 [5 6]]
transpose:
 [[1 4]
 [2 5]
 [3 6]]
astype(float):
 [[1. 2. 3.]
 [4. 5. 6.]]
original a:
 [[1 2 3]
 [4 5 6]]
copied (changed):
 [[999   2   3]
 [  4   5   6]]
sum (전체): 21
sum (행별): [ 6 15]


In [12]:
# 1. unique() – 배열에서 중복 제거된 고유값 반환
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_vals = np.unique(arr)
print("unique:", unique_vals)

# 2. zeros() – 지정된 크기의 배열을 0으로 초기화
zeros_arr = np.zeros((2, 3))
print("zeros:\n", zeros_arr)

# 3. ones() – 지정된 크기의 배열을 1로 초기화
ones_arr = np.ones((3, 2), dtype=int)
print("ones:\n", ones_arr)

unique: [1 2 3 4]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1 1]
 [1 1]
 [1 1]]


In [13]:
# 1. np.arange(start, stop, step)
a = np.arange(0, 10, 2)  # 0부터 9까지 값을 2씩 건너뛰며 생성
# 2. np.linspace(start, stop, num)
b = np.linspace(0, 1, 5)  # 0에서 1사이 구간에 대해 5개 값을 같은 간격으로 생성
print(a)
print(b)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [14]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
a + b, a - b, a * b, a / b

(array([11, 22, 33]),
 array([ 9, 18, 27]),
 array([10, 40, 90]),
 array([10., 10., 10.]))

In [18]:
# 브로드캐스팅 연산(배열의 형태가 서로 다른 연산)
a = np.array([10, 20, 30])
b = np.array([[10, 20, 30], [40, 50, 60]])
c = np.array([1, 2, 3])
a * 10, b + c, b * c

(array([100, 200, 300]),
 array([[11, 22, 33],
        [41, 52, 63]]),
 array([[ 10,  40,  90],
        [ 40, 100, 180]]))