# Ch02 연습문제

## 1. 다음 코드를 실행했을 때 출력될 값을 에측하시오.

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.ndim, a.shape, a.size, a.dtype)
# 차원, 모양, 크기, 자료형

2 (3, 2) 6 int64


## 2. a.reshape(3, 2)과 a.transpose()의 차이점에 대해 배열 a = np.array([1, 2, 3], [4, 5, 6]])를 기준으로 설명하시오.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.reshape(3, 2))
print(a.transpose())
# 모양 바꾸기, 전치

[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 3. 다음 코드의 실행 결과는?

In [4]:
a = np.array([3, 3, 2, 1, 2, 1])
print(np.unique(a))
# 중복값 제거 후 정렬

[1 2 3]


# 4. 다음 코드에서 어떤 결과가 출력될 지 예측하고, 브로드캐스팅이 어떻게 작용했는지 설명하시오.

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)

# 배열 형태가 다를 경우 크기가 작은 쪽 배열이 확장

[[11 22 33]
 [14 25 36]]
